[[acknowledgments]]
[preface]
== Acknowledgments

표지에는 두 사람의 이름만 올라가 있지만, 이 책은 우리 삶과 커리어 전반에 걸쳐 수백, 아니 수천 명의 사람들과 나눈 대화의 산물입니다. 여기 잠시나마 이 책의 많은 유익한 부분에 책임이 있는 분들께 감사 인사를 전합니다. (늘 그렇듯, 실수는 전적으로 우리의 몫입니다.)

오라일리 미디어의 동료들에게 감사드립니다. 더 넓은 독자를 향해 쓰도록 격려해 준 Mike Loukides, 그리고 두 분의 두려움 없는 편집자 Brian Anderson, Mary Treseler—특히 Mary의 격려와 인내, 때로는 다그침이 없었다면 이 책은 존재하지 못했을 것입니다.

link:$$http://sunnibrown.com$$[]의 Sunni Brown과 Amber Lewis에게도 감사드립니다. 뛰어난 일러스트로 책에 생명을 불어넣어 주셨습니다. 여러분과 함께 일하는 일은 진정한 기쁨이었습니다.

수많은 제안과 아이디어, 수정으로 책을 단단하게 만들어 준 기술 검토자들에게 감사드립니다. Dustin Boswell, Trevor Foucher, Michael Hunger, Jonathan LeBlanc, Piaw Na, Jack Welch. 원고를 미리 읽고 우리의 뻔뻔한 실수들을 잡아준 친구와 동료들에게도 감사드립니다. Dave Baum, Matt Cutts, Will Robinson, Bill Duane. 그리고 늘 조언을 아끼지 않는 멋진 친구들: Karl Fogel, Jim Blandy, Matt Braithwaite, Danny Berlin, Chris DiBona. 아이디어와 제안을 주신 Linda Stone, DeWitt Clinton, Bruce Johnson, Roland McGrath, Amit Patel께도 감사드립니다.

구글—특히 구글 시카고 엔지니어링 팀—에게도 감사드립니다. 매일 함께 일하는 것 자체가 환상적이었습니다. 여러분의 지원과 아이디어, 제안 덕분입니다.

특별히 우리의 멘토이자 스승인 분들께 감사드립니다. Bill Coughran, Steve Vinter, Alan Eustace, Stu Feldman, Eric Schmidt. 그분들의 지혜 중 작은 일부라도 이 페이지에 담으려 했습니다.

Brian Robinson과 Yvonne Ellison-Sandler에게도 특별한 감사의 마음을 전합니다. 멘토링과 조언, 가르침 덕분입니다.

아파치 소프트웨어 재단(ASF)에도 감사드립니다. 우리를 맞아 주셨을 뿐 아니라, 커뮤니티와 협업에 집중하는 태도 자체가 큰 본보기가 되었습니다.

가까운 모든 친구들에게도 감사합니다. 여러분 덕에 우리는 정말 풍요로운 사람들이 되었습니다. 그렇게 쳐다보지 마세요—본인들이 누군지 알잖아요.

이 책의 많은 부분은 시카고의 사랑스럽고 아늑한 Filter Cafe에서 구상되고 개요가 잡히고 쓰였습니다.

[[from_fitz]]
=== Fitz로 부터

아내 Marie에게 큰 감사를 전합니다. 당신의 격려, 이해, 인내—항상 나에게 영감이 됩니다. 늘 응원해 준 엄마에게도, 그리고 "사람은 식물과 같다"는 비유를 들려준 장모님 Rita Gumler에게도 감사드립니다.

Ben에게: 우리가 서로를 안 지 16년, 세 곳에서 함께 일했고, 세 권의 책을 함께 썼습니다. 매일 같이 일하지 못하는 지금이 아쉽습니다. 이 기묘하고 멋진 여정을 함께해 줘서 고마워요—당신은 훌륭한 친구이자 스승이었습니다.

마지막으로, 내 (어휴) 21년의 소프트웨어 엔지니어링 경력 동안 함께 일한 모든 분들께 감사드립니다. 놀라운 여정이었고, 매일 누군가에게서 무언가를 배웠습니다.

[[from_ben]]
=== Ben으로 부터

아내 Frances에게 적절한 말을 찾기 어렵습니다. 이 책뿐 아니라 지난 몇 년간 내가 벌인 열두 개쯤 되는 다른 창작 프로젝트들까지도, 그녀가 내게 허락한 '공간'이 없었다면 불가능했을 것입니다. 조용하지만 단단한 그 지지가 없었다면 어떤 것도 일어나지 않았겠죠.

Fitz에게: 이제 우리가 서로의 문장을 마저 이어 줄 정도가 되었으니, 오래된 부부 같다고 해도 되겠지요. 누군가와 함께 발표하는 일이 이렇게 즐거울 줄 몰랐습니다. 소프트웨어를 쓰고 책을 함께 쓰는 일도요. 우리에게 주어진 놀라운 기회들—정말 고마워요. 많은 걸 배웠습니다.

마지막으로, 실리콘밸리의 별난 사람들과 조직들에게도 감사드립니다. 그 기묘한 세계로 나를 들여보내 주지 않았다면, 이 모든 경험은 불가능했을 겁니다.

[[about_the_authors]]
=== 저자에 관해

Brian Fitzpatrick는 Tock의 창립자이자 CTO입니다. 2005년 Ben과 함께 구글 시카고 엔지니어링 오피스를 시작했고, Data Liberation Front와 Transparency Engineering을 포함한 구글의 여러 글로벌 엔지니어링 노력을 이끌었습니다. 또한 구글의 오픈 데이터 활동의 내부 자문을 맡았고, 그 전에는 Google Code와 Google Affiliate Network 팀을 이끌었습니다. 구글에 합류하기 전에는 Apple, CollabNet, 시카고의 한 로컬 개발사에서 엔지니어로 일했습니다.

Brian은 수많은 글을 쓰고 수십 차례 발표했으며, pass:[<a class="orm:hideurl" href="http://shop.oreilly.com/product/0636920018025.do"><em>Team Geek: A Software Developer's Guide to Working Well with Others</em></a>]를 공동 집필했습니다. 또한 pass:[<a class="orm:hideurl" href="http://shop.oreilly.com/product/9780596004484.do"><em>Version Control with Subversion</em></a>] (현재 2판), pass:[<a class="orm:hideurl" href="http://shop.oreilly.com/product/9780596100292.do"><em>Unix in a Nutshell</em></a>], pass:[<a class="orm:hideurl" href="http://shop.oreilly.com/product/9780596154493.do"><em>Linux in a Nutshell</em></a>]에도 기여했습니다.

Brian은 Loyola University Chicago에서 고전학(라틴 전공, 그리스어 부전공, 순수미술·도자 집중)을 전공했고, 시카고에 거주합니다.

Ben Collins-Sussman은 Subversion 버전 관리 시스템의 창립 개발자 중 한 명입니다. 시카고에서 구글 엔지니어링 오피스를 공동 설립했고, Google Code를 출범시켰으며, 디스플레이 광고 팀 두 곳을 이끌었습니다. 현재는 구글 검색 인프라를 뒷받침하는 팀들을 관리하고 있으며, 시카고 사이트 리드를 맡고 있습니다. 그 외에도 인터랙티브 픽션 집필, 블루그래스 밴조와 재즈 피아노 연주, 뮤지컬 작곡, 아마추어 무선, 사진 등 다양한 취미를 즐깁니다. 시카고 태생으로 University of Chicago에서 수학을 전공(수학 전공, 언어학 부전공)했고, 현재도 아내와 아이들, 고양이들과 함께 시카고에 살고 있습니다.
